### ISSUE TITLE
Проверка дз №2

### ISSUE THREAD

**Issue by YuriyBiznigaev** [donatio-nikolashin/ios-edu#2]
@donatio-nikolashin 

1. 2-ю дз вынести в ветку отдельную от дз 1

2. не могу запустить на ios14, нужно уменьшить значение target distribution:
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/75571475/161397108-6c69e263-9abb-48ce-8c8b-c45e1dba03b3.png">

3. по двойному нажатию на изображение должна происходить анимация сердечка поверх изображения. Сейчас анимация срабатывает даже если лайк не добавляется. Нужно оставить анимацию только лайк добавляется.

4. добавить плюралы для числительных в лайках: 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/75571475/161398728-65fb4fd4-0a53-44bf-ae3a-37ebde7b9285.png">

**Comment by donatio-nikolashin** [comment]
1) Вынес в отдельный PR https://github.com/donatio-nikolashin/ios-edu/pull/3
2) Не могу найти target distribution. Deployment target установлен на 14.0:
<img width="533" alt="Снимок экрана 2022-04-03 в 00 54 27" src="https://user-images.githubusercontent.com/233153/161402571-fc616460-ffa5-41fe-8a43-c4c219d5b260.png">
<img width="348" alt="Снимок экрана 2022-04-03 в 00 58 15" src="https://user-images.githubusercontent.com/233153/161402663-2954493f-20a1-4e68-afd6-e674398a295f.png">

3) Исправил.
4) Кажется, что исправил:
<img width="472" alt="Снимок экрана 2022-04-03 в 00 51 12" src="https://user-images.githubusercontent.com/233153/161402458-c8f87fac-0585-43e3-9117-ff6b70f90e99.png">
